### ISSUE TITLE
Adguard looks like its disabled by the chrome extension but its not

### ISSUE THREAD

**Issue by Ncage1974** [AdguardTeam/BrowserAssistant#54] opened 2022-01-09 19:04 UTC
So i've been noticing this for maybe a month or so (i use multiple computers & its the same on all). Adguard looks its disabled on the site your own (its greyed out). Simply click the extension turns the icon green. This of course is misleading since it looks like adguard is not active on the site. Here is an example:  
![adguard](https://user-images.githubusercontent.com/1213549/148696437-9f9fb0e1-55f2-4fcc-89a8-93ecb0e6b6b4.gif)
 I seen a similar issue #46 but this didn't have to do with disabling anything (it just looks disabled).   

**Info**
Chrome Version Version 97.0.4692.71 (Official Build) (arm64)
Adguard Browser Assistant Version 1.2.2

**Comment by ameshkov** [comment] 2022-01-10 10:58
Duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/1025

**Closed by ameshkov** 2022-01-10 10:58 UTC
